// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace GrawApp
{
	public partial class RawViewController : UIViewController
	{
		public RawViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
