// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace GrawApp
{
	public partial class StationDataTabBarController : UITabBarController
	{
		public StationDataTabBarController (IntPtr handle) : base (handle)
		{
		}
	}
}
