// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using GrawApp.Controller.Messages;
using UIKit;

namespace GrawApp
{
	public partial class MessageEndViewController : MessageBaseViewController
	{
		public MessageEndViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            InitializeIndicator(View);
            GetText(false);
        }
        public override void UpdateText(string text)
        {
            BusyIndicator.Hidden = true;
            textView.Text = text;
        }
	}
}
