// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using GrawApp.Controller.Messages;
using UIKit;

namespace GrawApp
{
	public partial class MessagesViewController : MessageBaseViewController
	{
		public MessagesViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            InitializeIndicator(View);
            GetText(true);
        }

        public override void UpdateText(string text)
        {
            ActivityIndicator.StopAnimating();
            textView.Text = text;
        }
    }
}
