// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace GrawApp.View
{
	public partial class CustomRawCell : UITableViewCell
	{
		public CustomRawCell (IntPtr handle) : base (handle)
		{
		}
	}
}
