// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using GrawApp.Model;
using UIKit;

namespace GrawApp.Controller.Raw
{
	public partial class PageOneViewController : RawBaseViewController
	{
        RawDataRepository _dataRepository;
		public PageOneViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            _dataRepository = new RawDataRepository();
            TableView.Source = new RawValueTableViewSource(){DataRepository = _dataRepository};
            var appDelegate = UIApplication.SharedApplication.Delegate as AppDelegate;
            var rawData = appDelegate.RawData;

            if (rawData != null)
            {
                SetData(rawData);
            }
        }

        public override void SetData(RawData data)
        {
            _dataRepository.SetValue(data.Temperature, DataType.Temperature,"0.0","°C");
            _dataRepository.SetValue(data.Humdity, DataType.Humdity,"0","%");
            _dataRepository.SetValue(data.Pressure, DataType.Pressure,"0.0","mB");
            _dataRepository.SetValue(data.Altitude, DataType.Altitude,"0","m");
            _dataRepository.SetValue(data.WindSpeed, DataType.Windspeed,"0.0","m/s");
            _dataRepository.SetValue(data.WindDirection, DataType.Winddirection,"000","°");
            TableView.ReloadData();

        }
    }

    internal class RawValueTableViewSource : UITableViewSource
    {
        public RawDataRepository DataRepository { get; set; }
        public RawValueTableViewSource()
        {
            
        }
        public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
        {
            var cell = tableView.DequeueReusableCell("rawData") as CustomRawCell;
            var item = DataRepository.GetItem(indexPath.Row);
            if (item != null)
            {
                cell.HeaderLabelOutlet.Text = item.HeaderName;
                cell.ImageView.Image = new UIImage(item.ImageName);
                cell.ValueLabelOutlet.Text = item.Value;
            }
            return cell;
        }

        public override nint RowsInSection(UITableView tableview, nint section)
        {
            return DataRepository.DataList.Count;
        }
    }
}
