// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace GrawApp.Controller.Raw
{
	public partial class PageTwoController : UIViewController
	{
		public PageTwoController (IntPtr handle) : base (handle)
		{
		}
	}
}
