// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace GrawApp.Controller.Raw
{
    public partial class CustomRawCell : UITableViewCell
    {
        

        public UIImageView ImageViewOutlet { get => CustomImage; set => CustomImage = value; }
        public UILabel HeaderLabelOutlet { get => HeaderLabel; set => HeaderLabel = value; }
        public UILabel ValueLabelOutlet { get => ValueLabel; set => ValueLabel = value; }

        public CustomRawCell(IntPtr handle) : base(handle)
        {
        }
    }
}
