// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using Foundation;
using UIKit;

namespace GrawApp.Controller.Raw
{
	public partial class RawContentViewController : UIViewController
	{
        
        RawPageViewController _rawPageViewController;
		public RawContentViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            _rawPageViewController = new RawPageViewController();

            var sampleFrame = new CGRect(SubView.Bounds.Location.X,
                                         SubView.Bounds.GetMinY(),
                                         SubView.Bounds.Width,
                                         SubView.Bounds.Height);
            _rawPageViewController.View.Frame = sampleFrame;
            SubView.Add(_rawPageViewController.View);
        }
    }
}
