// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace GrawApp.View
{
	public partial class RawContentViewController : UIViewController
	{
		public RawContentViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
