// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using CoreGraphics;
using Foundation;
using GrawApp.Model;
using UIKit;

namespace GrawApp.Controller.Raw
{
    public partial class RawPageViewController : UIPageViewController,ISetData<RawData>
    {
        public UIPageControl PageControl { get; set; }
        List<ISetData<RawData>> _setDataList;
        public RawPageViewController(IntPtr handle) : base(handle)
        {
        }

        public RawPageViewController() : base(UIPageViewControllerTransitionStyle.Scroll, UIPageViewControllerNavigationOrientation.Horizontal)
        {
            
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            _setDataList = new List<ISetData<RawData>>();
            //NavigationController?.InteractivePopGestureRecognizer.Enabled = false;
            var rawDataSource = new RawPageDataSource();
            rawDataSource.SetDataList = _setDataList;
            PageControl = new UIPageControl();

            //PageSource.PageControl = PageControl;
            rawDataSource.ParentViewController = this;
            this.DataSource = rawDataSource;


            ConfigurePages();
            var controller = rawDataSource.GetViewControllerByIndex(0);

            SetViewControllers(new UIViewController[] { controller }, UIPageViewControllerNavigationDirection.Forward,
                                true, null);
        }

        public void ConfigurePages()
        {
            PageControl = new UIPageControl(new CGRect(0,
                                                       this.View.Bounds.GetMinX(),
                                                       UIScreen.MainScreen.Bounds.Width,
                                                       height: 50));
            PageControl.Pages = 2;
            PageControl.CurrentPage = 0;
            PageControl.Enabled = true;
            PageControl.TintColor = UIColor.Black;
            PageControl.PageIndicatorTintColor = UIColor.LightGray;
            PageControl.CurrentPageIndicatorTintColor = UIColor.Black;
            this.View.AddSubview(PageControl);
        }

        public void SetData(RawData data)
        {
            foreach (var item in _setDataList)
            {
                item?.SetData(data);
            }

        }

        public class RawPageDataSource : UIPageViewControllerDataSource
        {
            public List<ISetData<RawData>> SetDataList { get; set; } = new List<ISetData<RawData>>();
            public List<string> ViewControllerIdentifiers { get; set; } = new List<string> { "Page1", "Page2" };
            //public UIPageControl PageControl { get; set; }

            public RawPageViewController ParentViewController { get; set; }

            int PreviousIndex = 0;

            public override UIViewController GetNextViewController(UIPageViewController pageViewController, UIViewController referenceViewController)
            {
                var pageContent = referenceViewController as UIViewController;

                Console.WriteLine($"Next Page -- {pageContent.RestorationIdentifier}");
                if (pageContent == null)
                {
                    return null;
                }
                var index = ViewControllerIdentifiers.IndexOf(pageContent.RestorationIdentifier);
                Console.WriteLine($"Next Page -- Index:{index}");
                ParentViewController.PageControl.CurrentPage = index;
                if (index >= ViewControllerIdentifiers.Count - 1)
                {
                    return null;
                }

                index++;
                return GetViewControllerByIndex(index);
            }

            public override UIViewController GetPreviousViewController(UIPageViewController pageViewController, UIViewController referenceViewController)
            {
                var pageContent = referenceViewController as UIViewController;
                Console.WriteLine($"Previuous Page -- {pageContent.RestorationIdentifier}");
                if (pageContent == null)
                {
                    return null;
                }
                var index = ViewControllerIdentifiers.IndexOf(pageContent.RestorationIdentifier);
                ParentViewController.PageControl.CurrentPage = index;
                Console.WriteLine($"Previuous Page -- Index:{index}");
                //var indexCheck = viewControllerIdentifiers.IndexOf();

                if (index <= 0)
                {
                    return null;
                }

                index--;
                return GetViewControllerByIndex(index);
            }


            public UIViewController GetViewControllerByIndex(int index)
            {

                var storyboard = UIStoryboard.FromName("Main", null);
                var nc = storyboard.InstantiateViewController(ViewControllerIdentifiers[index]) as RawBaseViewController;
                //nc.Index = index;
                var exists = SetDataList.Exists(x=>x == nc);
                if (!exists)
                    SetDataList.Add(nc);
                
                return nc;

            }
        }
    }
}