// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace GrawApp.Controller.Raw
{
	public partial class RawValueTableViewController : UITableViewController
	{
		public RawValueTableViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            //TableView.Source = new RawValueTableViewSource();
        }
    }

   /* internal class RawValueTableViewSource : UITableViewSource
    {
        RawDataRepository DataRepository;
        public RawValueTableViewSource()
        {
            DataRepository = new RawDataRepository();
        }
        public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
        {
            var cell = tableView.DequeueReusableCell("rawData") as CustomRawCell;
            var item = DataRepository.GetItem(indexPath.Row);
            if(item != null)
            {
                cell.HeaderLabelOutlet.Text = item.HeaderName;
                cell.ImageView.Image = new UIImage(item.ImageName);
                cell.ValueLabelOutlet.Text = item.Value;
            }
            return cell;
        }

        public override nint RowsInSection(UITableView tableview, nint section)
        {
            return DataRepository.DataList.Count;
        }
    }*/
}
